### PR TITLE
Adds pz routing video

### PR DESCRIPTION
**Pull request by ZPain8464**
This is a draft PR with the Routing in PZ video. You can find the video on `/docs/capabilities/routing`.

### CODE REVIEW

**Comment by ZPain8464** [comment]
My only concern is the video quality. It's somewhat blurry, which makes it hard to read tooltips and some of the text.

**Review by cmo-pomerium — APPROVED** [review]
LGTM. I think this video is pretty good. Achieves everything we want out of them.

**Comment by desimone** [comment]
Why not on the fundamentals page (too?) seems more aligned

https://deploy-preview-1325--pomerium-docs.netlify.app/docs/courses/fundamentals/build-routes

**Comment by ZPain8464** [comment]
I need to re-shoot this, because the From: URL now provides a dropdown to select the schema.

**Pull request merged**
