### PR TITLE
add cookie-same-site option

### PR DESCRIPTION
**Pull request by calebdoxsey**
For: https://github.com/pomerium/pomerium/pull/4148

### CODE REVIEW

**Comment by ZPain8464** [comment]
@calebdoxsey I thought we weren't including this in the v22 release, otherwise I would've tackled this for you. Thanks for adding it.

**Comment by calebdoxsey** [comment]
It's not in v22.

**Comment by calebdoxsey** [comment]
We have a bit of a chicken and egg problem because updating the console with new configuration options requires updates to `reference.json`.

**Review by ZPain8464 — APPROVED** [review]

**Comment by ZPain8464** [comment]
Closes #591

**Pull request merged**
